### ISSUE TITLE
No compatible with py_image?

### ISSUE THREAD

**Issue by yohanyflores** [kku1993/bazel-hermetic-python#1]
Cheers...

Really a great job! I have been testing this and it works perfectly.

Some of the features I try to do have to do with creating a docker image, which I do with py_image.

The image is built correctly!

However when executing it, it doesn't get the python interpreter.

It is created in the runfiles as a symlink destined for the bazel cache.
 
But symlinks are not supported when building the docker image.

I have been learning bazel for just under a week, I wanted to ask you: Is there a way to make a copy of the interpreter and not a symbolic reference to the cache?

```
lrwxrwxrwx  1 yohany yohany  111 may 30 16:38 python_bin -> /home/yohany/.cache/bazel/_bazel_yohany/e4a7ca4e1b4c2a1e43cdf1e4911e158f/external/python_interpreter/python_bin
```

**Comment by kku1993** [comment]
Thanks for trying this out and your great feedback! And also welcome to bazel! :)

I've updated a repo to include a demo on building docker images with this setup [1]. Essentially the trick is to specify a base for `py3_image` that contains a python interpreter with the same version as the you built with `http_archive`.

There are some workarounds needed such as specifying your python toolchain last in `WORKSPACE` [2] and adding symlinks to the base image [3], but the repo should contain a working version for you to play around (I've only tested this on ubuntu 18.04, docker 19.03.8).

Let me know if you run into any issues.

[1] https://github.com/kku1993/bazel-hermetic-python/commit/895408bf0d0e17ddd2543acb14a2c4f7a9e18f68
[2] https://github.com/kku1993/bazel-hermetic-python/blob/895408bf0d0e17ddd2543acb14a2c4f7a9e18f68/WORKSPACE#L113
[3] https://github.com/kku1993/bazel-hermetic-python/blob/895408bf0d0e17ddd2543acb14a2c4f7a9e18f68/BUILD.bazel#L42

**Comment by yohanyflores** [comment]
Thanks for your prompt response!

Today during the day, I will be reviewing your changes and I will give you a feedback.

**Comment by yohanyflores** [comment]
Regards.

Make the implementation of your ideas ...

Wow this works wonders!

I had already tried something similar, but it did not work for me, in the docker it always tried to find the registered toolchain, and not the one found in the image. The key point, (which I would have never seen!) Is to register the python toolchain at the end of the workspace. That completely saved my day !!!

Thank you very much for that great contribution!

**Comment by kku1993** [comment]
Glad to hear that it works for you :tada: 

Good luck on all your bazel and python endeavours!
