### ISSUE TITLE
ssl issues under ubuntu

### ISSUE THREAD

**Issue by qfliu** [kku1993/bazel-hermetic-python#5]
When I was running test under ubuntu, I am getting the following error:
```
AttributeError: module 'websocket._ssl_compat' has no attribute 'ssl'
``` 

I am setting it up with python3.7.2

Have you ever run into this error before?

**Comment by kku1993** [comment]
I have not seen this error before.

Is it an error from building the python interpreter, or an error when running the test? If it's the latter, I think it's a problem with the websocket python package version that you're using. Make sure you're using a `rules_python` version that supports setting a `python_interpreter_target` [1].

[1] https://github.com/kku1993/bazel-hermetic-python/blob/0a595dc7db83f50f1fa43cbe7e4d2c35fa60e9c8/WORKSPACE#L58

**Comment by qfliu** [comment]
I tried to run
```
..../python_interpreter/bazel_install/bin/python3
Python 3.7.2 (default, Nov 18 2020, 02:19:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.cache/bazel/_bazel_root/82babfd27d34e851ff8b81bfb98fefcd/external/python_interpreter/bazel_install/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
```
it does not seem tied to websocket.

**Comment by kku1993** [comment]
Do you have `openssl` installed? You need to have it when building the python interpreter to enable SSL support.

**Comment by rlaakkol** [comment]
Ran into this too, installing the `libssl-dev` package solves this on ubuntu. Additionally, if you run into `ModuleNotFoundError: No module named '_ctypes'`, that one is solved by installing `libffi-dev`.
