### ISSUE TITLE
Python build not deterministic

### ISSUE THREAD

**Issue by aaliddell** [kku1993/bazel-hermetic-python#7]
The current build steps produce a python binary that is different on each clean rebuild, due to containing the build timestamp. This results in cache failures and unnecessary rebuilds if using a remote cache for example. You can see this by looking at `sys.version` for any python install: `'3.7.6 (default, Jan  6 2020, 14:02:36) \n[GCC 7.4.0]'`

The following change to the `make` command produces a bit-identical Python binary between rebuilds (assuming same path and using gcc) by forcing the timestamp to be 0:

```SOURCE_DATE_EPOCH=0 make -j $(nproc) ARFLAGS='rvD'```

This also adds `-j` to speed up the build by using all CPU cores. Note, the `ARFLAGS` may not be necessary, depending on whether your specific build of `ar` has deterministic builds enabled by default.

After this, `sys.version` is now constant: `'3.8.10 (default, Jan  1 1970, 00:00:00) \n[GCC 7.5.0]'`

**Comment by kku1993** [comment]
This is awesome, cheers!
