### ISSUE TITLE
ar: illegal option -- D on Macos Big Sur

### ISSUE THREAD

**Issue by Sebelino** [kku1993/bazel-hermetic-python#9]
I haven't been able to `bazel build` the project with the current Python 3.8.3 on Macos Big Sur due to [this issue](https://stackoverflow.com/questions/65444084/pyenv-issues-with-big-sur-11-1), so I tried `3.9.6` instead. That went better, but I now get the following error:

```
/Library/Developer/CommandLineTools/usr/bin/ar: illegal option -- D
```

It turns out that `ar` on Macos does not support the D modifier:
```
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
```

It looks like building on Macos broke after this change: https://github.com/kku1993/bazel-hermetic-python/commit/c2eee5a6876e74a496de59d36acafcd730be6bdd#diff-5493ff8e9397811510e780de47c57abb70137f1afe85d1519130dc3679d60ce5R26

Changing
```
ARFLAGS='rvD'
```
to
```
ARFLAGS='rv'
```
fixed the build for me.

I propose removing the `D` modifier since it appears to be the default on Linux anyway:
```
$ echo $OSTYPE
linux-gnu

$ ar 2>/dev/null | grep "\[D\]"
  [D] - use zero for timestamps and uids/gids (default)
```

Environment details:
```
% echo $OSTYPE
darwin20.0
% sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
```

**Comment by kku1993** [comment]
Thanks for the suggestion! I'm glad the issue have been resolved for you.

I've updated the repo to check for the `D` modifier. While it seems like a lot of linux distributions have it set by default [1, 2], I just want to make this repo more bullet proof for people trying this out on the one-off distribution that does not :)

[1] https://wiki.debian.org/ReproducibleBuilds/TimestampsInStaticLibraries
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1124342
